# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 73dc4d4f0c5eabf5ce1bc353527c904913c8ed902b9012979b6e767dee201de4571af98a4f0853b2fcf2c1a3f8f8e834ed378f56622d5963dcfd638f7915c22d

test:
  secret_key_base: 79e6a1f087bf46de5637b065fe2e49d842011846df2c3eb5a01d4356082d0046ed24d612441f77b7b830db95ae30a7cf6b3ea263aa49a9bf2188f8d61390e14d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
